name: run

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: 30 00 * * *

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm install node-fetch
      - run: npm run main
        env:
          GLADOS: ${{ secrets.GLADOS }}
          NOTIFY: ${{ secrets.NOTIFY }}
          NOTIFYTIAN: ${{ secrets.NOTIFYTIAN }}
          
